# Generated by Django 4.1.3 on 2022-12-09 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0009_vaga_email'),
        ('vagas', '0003_alter_emails_vaga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emails',
            name='vaga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='empresa.vaga'),
        ),
    ]
