# Generated by Django 4.1.3 on 2022-11-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo_empresa')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('cidade', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=50)),
                ('caracteristica_empresa', models.TextField()),
                ('nicho_mercado', models.CharField(choices=[('M', 'Marketing'), ('T', 'Tecnologia'), ('N', 'Nutrição'), ('D', 'Designer'), ('A', 'Advogado')], max_length=5)),
                ('tecnologias', models.ManyToManyField(to='empresa.tecnologias')),
            ],
        ),
    ]
