# Generated by Django 4.1.3 on 2022-11-12 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_rename_tecnologias_empresa_tecnologia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cidade',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='endereco',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nicho_mercado',
            field=models.CharField(choices=[('M', 'Marketing'), ('N', 'Nutrição'), ('D', 'Design'), ('T', 'Tecnologia'), ('A', 'Advgogado')], max_length=3),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nome',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('nivel_experiencia', models.CharField(choices=[('E', 'Estágio'), ('J', 'Júnior'), ('P', 'Pleno'), ('S', 'Sênior')], max_length=2)),
                ('data_final', models.DateField()),
                ('status', models.CharField(choices=[('I', 'Interesse'), ('C', 'Currículo enviado'), ('E', 'Entrevista'), ('D', 'Desafio técnico'), ('F', 'Finalizado')], max_length=30)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='empresa.empresa')),
                ('tecnologia_dominadas', models.ManyToManyField(to='empresa.tecnologia')),
                ('tecnologia_estudar', models.ManyToManyField(related_name='estudar', to='empresa.tecnologia')),
            ],
        ),
    ]
