# Generated by Django 4.1.3 on 2022-11-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0005_alter_empresa_cidade_alter_empresa_endereco_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nicho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nicho', models.CharField(choices=[('M', 'Marketing'), ('N', 'Nutrição'), ('D', 'Design'), ('T', 'Tecnologia'), ('A', 'Advogado')], max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='nicho_mercado',
        ),
        migrations.AddField(
            model_name='empresa',
            name='nicho_mercado',
            field=models.ManyToManyField(to='empresa.nicho'),
        ),
    ]
