# Generated by Django 4.1.3 on 2022-11-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0006_nicho_remove_empresa_nicho_mercado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='nicho_mercado',
        ),
        migrations.DeleteModel(
            name='Nicho',
        ),
        migrations.AddField(
            model_name='empresa',
            name='nicho_mercado',
            field=models.CharField(choices=[('M', 'Marketing'), ('N', 'Nutrição'), ('D', 'Design'), ('T', 'Tecnologia'), ('A', 'Advogado')], default=2, max_length=50),
            preserve_default=False,
        ),
    ]
