# Generated by Django 4.1.3 on 2022-11-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0007_remove_empresa_nicho_mercado_delete_nicho_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='nicho_mercado',
            field=models.CharField(choices=[('M', 'Marketing'), ('N', 'Nutrição'), ('D', 'Design'), ('T', 'Tecnologia'), ('A', 'Advocacia')], max_length=50),
        ),
    ]
