# Generated by Django 4.1.3 on 2022-12-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0008_alter_empresa_nicho_mercado'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
